- lib/Spot/Relation/HasManyThrough.php
The `$entityRelations` variable always ends up empty. So the next `foreach()` never populates related objects back into the original Collection.
So currently (before this patch is applied), I believe all hasManyThrough suffer from the N+1 problem.
This fix is a prerequisite for #54 , it needs to be merge first otherwise we introduce a bug.
> Bugfix on hasManyThroughRelation not dispatching related objects properly

- lib/Spot/Relation/HasMany.php
- lib/Spot/Relation/HasManyThrough.php
- lib/Spot/Relation/RelationAbstract.php
I'll try to describe the problem I've been running into as clearly as possible. It's not so easy, but I'll do my best:
1. Load a Collection of Post entities with their tags `$posts->all()->with(['tags']);`
2. Internally, Spot calls `Mapper->collection()` to create the Collection then calls `Mapper->with` to load the requested relations. Then this happens (I'm only putting the critical path):
```php
$singleEntity = $collection->first();
$relationObject = $singleEntity->relation($relationName);
$relationObject->eagerLoadOnCollection($relationName, $collection);
```
And then inside **eagerLoadOnCollection()**:
```
// Set relation collections back on each entity object
foreach ($collection as $entity) {
if (isset($entityRelations[$entity->$relationEntityKey])) { …
```
> Set relations on entities when eagerLoading, even when the entity has no related objects

- lib/Spot/Mapper.php
Otherwise PhpStorm won't know what to do after a ->where().
> Fix docblocks for Query

- lib/Spot/Mapper.php
I think that multiple NULL values should be allowed.
```php
class ExampleEntity extends \Spot\Entity
{
public static function fields()
{
return [
'vat_number' => ['type' => 'string', 'unique' => true]
];
}
```
```php
$result = $mapper->insert([
'vat_number' => null
]);
```
```sql
'SELECT * FROM example_entity WHERE `example_entity`.`vat_number` IS NULL
```
```php
Unable to insert new Entity\ExampleEntity- Errors: array ( 'vat_number' => array (0 => 'Vat Number \'\' is already taken.))
```
> Unique fields should only be validated if the field isn't NULL

- lib/Spot/Entity.php
- tests/SpotTest/Entity.php
- tests/SpotTest/RelationsEagerLoading.php
When running toArray on an Entity, the eager loaded record(s) are never filled. With this update, if you have eager loaded a relationship using ->with, you will be able to run toArray from an entity and get the data from the relationship.
> Perform toArray on eager loaded relationships when running toArray on Entity

- lib/Spot/Mapper.php
Much easier to debug than "Missing argument 1 for Spot\Entity::get()".
> Throw Exception when primary key is missing

- lib/Spot/Mapper.php
- tests/SpotTest/Validation.php
There are cases when you want to save an entity without validating. For example when creating a stub entity in database which user must then fill with missing properties. This pull request adds possibility of disabling validation by passing boolean `false` as `validate`option.
```php
$mapper->save($entity, ['validate' => false]);
```
> Enable disabling validation via options

- README.md
Noticed this was missing compared to the other examples.
> Fixed missing arguments for relations()

- lib/Spot/Config.php
- lib/Spot/Locator.php
- lib/Spot/Mapper.php
- lib/Spot/Relation/HasMany.php
- lib/Spot/Relation/HasManyThrough.php
- lib/Spot/Relation/RelationAbstract.php
* Replaced `Spot\Classname` with FQCN `\Spot\Classname`
* Replace `Spot_Adapter` with `\Doctrine\DBAL\Connection`
Auto-completion was all messed up when trying to use `$mapper->connection()` so I cleaned-up :-)
> Cleaning-up PHP doc @return types

- lib/Spot/Entity.php
- tests/SpotTest/RelationsEagerLoading.php
This helps prevent endless loop of loading relationships. It also allows users to specify the depth of the toArray output.
> Add loadRelations option to data/toArray to support limiting depth of to Array

- composer.json
Spot2 relies on the developer to have phpunit installed globally. This commit adds phpunit via composer.
> Adding PHPUnit to the dev requirements for composer

- .travis.yml
This PR
:information_desk_person: Seems like Travis even points this out now, see this
For reference, see http://docs.travis-ci.com/user/migrating-from-legacy.
> Fix: Direct builds to container-based infrastructure

- .travis.yml
> Fix: Cache dependencies installed with Composer between builds

- composer.json
> Fix: One require-dev section should be enough

- phpunit.xml
This PR
See https://travis-ci.org/vlucas/spot2/jobs/70327855#L208.
> Fix: Add whitelist configuration

- lib/Entity.php
> Fix: Entity::__get() only accepts one argument

- lib/Entity.php
> Fix: Entity::set() doesn't return anything

- .travis.yml
> Fix: Use the same version of phpunit on Travis as required with Composer

- lib/Entity/Manager.php
- lib/Mapper.php
- lib/Query.php
- lib/Query/Resolver.php
- tests/Entity/Legacy.php
- tests/FieldAlias.php
Added support for column aliases with the `column` keyword when defining an entity and its fields.
> Fix #97 with support for field/column aliases

- lib/Entity.php
- tests/ArrayObjectTypes.php
- tests/Entity/ArrayObjectType.php
Modified the getter-code to fix #121 
If the value in the field is an array or an object, __get will always return a reference to the field in Entity::_dataModified. That way Entity::_data stays clean, so any change can be detected afterwards
> Detect modificiations to object and array fields

- lib/Mapper.php
- lib/Query/Resolver.php
- phpunit_sqlite.xml
- tests/Entity/Schema/Test.php
- tests/FieldAlias.php
- tests/QuerySql.php
- tests/SchemaQuerySql.php
- tests/Scopes.php
This pull request implements the feature requested in issue #126.
The schema (a.k.a. database) in which an entity table should be can be explicitly defined in an Entity class:
protected static $table = 'support.tickets'; // Schema `support`, `table tickets`
- Existing unit tests have been adapted to the new SQL statements.
- There is also a new test `SchemaQuerySql` using a new Entity `Schema\Test` to test this feature with and without quoting identifiers.
- This test is excluded from `phpunit_sqlite.xml` because this implementation does not work in SQLite.
- All MySQL and SQLite tests pass - could not test for PostgreSQL.
> Remove table aliases and allow explicit definition of a schema in Entity class

- lib/Entity/Manager.php
- tests/Entity/NotNullOverride.php
- tests/Manager.php
Currently if you have fields defined as below `notnull` will be `true` for all data columns. This is because `required` causes `notnull` default to `true`. You should however be able to manually set `notnull` to be `false` if you know what you are doing.
```php
public static function fields()
{
return [
"id"     => ["type" => "integer", "primary" => true],
"data1"  => ["type" => "string", "required" => true],
"data2"  => ["type" => "string", "required" => true, "notnull" => true],
"data3"  => ["type" => "string", "required" => true, "notnull" => false],
];
}
```
This pull request changes the behaviour so that `required` setting wont override user provided `notnull` setting when present.
> Honor given notnull setting in schema even if required setting is true

- lib/Mapper.php
- lib/Relation/RelationAbstract.php
- tests/Entity/Post.php
- tests/Entity/Post/Comment.php
- tests/Scopes.php
Mapper now defaults to entities' scopes instead of empty array. The method `scopes` was already defined in Entity, but I don't think it was used from what I saw in the code. 
Scopes can be used from relations:
```
//Get post with id 1, then its comments, then just yesterday's.
$yesterday_comments = $mapper->get(1)->comments->yesterday();
```
> Scopes enhancements

- lib/Relation/HasMany.php
- lib/Relation/HasManyThrough.php
As the title says. A simple solution for the case when you might have a lot of related entities and you only want to display a count of them. Also makes the relations behavior consistent with the entities themselves, as $comments->count() already created a count(*) style query, while $article->getComments()->count() loaded all related data and populated all entities, which isn't really intuitive and quite of an overkill when all you want to do is displaying a counter.
> Run count(*) queries when counting relations instead of eager loading all entities

- lib/Entity.php
see #131.
The problem was that get and set where not getting/setting the value from the same location (dataModified, data and relation). 
Set was looking in relations first while get was looking in relations last. I encountered the bug because I had a relation that had the same name as a property.
> Changed order in set to match the order of get (dataModified, data, relation)

- tests/Validation.php
Testing the validation failed because the test was comparing to the wrong message for an invalid e-mail address apparently (the shortest possible e-mail address seems to be 4 characters long, so the message returned by valitron seemed more correct then the one that was in the test)
> Validationmsg

- lib/Entity/Manager.php
- lib/Query/Resolver.php
Pull request to add foreign keys  (#77).
Adds the following options to the fields configuration:
- `foreignkey`: Defaults to false. If set to true, the foreign key will be added in migrations
- `onUpdate`: Defaults to null, valid options are: CASCADE, SET NULL, RESTRICT, NO ACTION. When left to null, it will be set to CASCADE during migration.
- `onDelete`: Defaults to null, valid options are: CASCADE, SET NULL, RESTRICT, NO ACTION. When left to null, it will be set to CASCADE if the field is `required`, else it will be SET NULL
I added `foreignkey` to prevent any regression from scripts that might behave inconsistently with the `onUpdate` and `onDelete` defaults.
> Added foreign keys from BelongsTo relations to the table schema #77

- lib/Mapper.php
- lib/Relation/BelongsTo.php
- lib/Relation/HasMany.php
- lib/Relation/HasManyThrough.php
- lib/Relation/HasOne.php
- lib/Relation/RelationAbstract.php
- tests/CRUD.php
- tests/Validation.php
Enables automatically saving relations when saving an entity.
Will only save loaded or explicitly set relations. It won't bother with lazy loaded relations as they have not been modified and do not need to be saved.
Adds a new option when saving to keep backward compatibility: `relations`, if set to true, all related entities will be saved at the same time as the entity.
The same option can be used with validation. So you can validate an entire tree of entities in one call.
The main entity will have the errors of all related entities under a key named from the relation name.
Example from the tests:
```php
$author = new \SpotTest\Entity\Author(['email' => 'test@example.com', 'password' => '123456']);
$post = $mapper->build([
'title' => 'Test',
'body' => 'Test description',
]); …
```
> Save relations

- lib/Query/Resolver.php
- tests/CRUD.php
- tests/Entity.php
- tests/Entity/PolymorphicComment.php
- tests/Entity/RecursiveEntity.php
- tests/Events.php
- tests/FieldAlias.php
- tests/ForeignKeys.php
- tests/Insert.php
- tests/QuerySql.php
- tests/Relations.php
- tests/RelationsEagerLoading.php
- tests/RelationsPolymorphic.php
- tests/Scopes.php
- tests/Transactions.php
Pull request to patch the addForeignKeys() function added in PR #136 
**Issue 1:** The $relations variable is empty and the migration fails (@Schrank could reproduce the problem).
**Issue 2:** If your foreign key is mapped to an aliased column then the migration fails.
**Example Entity:**
```php
class Example extends \Spot\Entity
{
protected static $table = 'example';
public static function fields()
{
return [
'id' => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
'officeId' => ['type' => 'integer', 'required' => true, 'column' => 'office_id']
];
}
public static function relations(Mapper $mapper, Entity $entity)
{
return [
'office' => $mapper->belongsTo($entity, 'Rendelo\Entity\Office', 'officeId')
];
}
}
```
> Patch for foreign keys (empty variable bug, alias support) #77 #136

- lib/Entity.php
In some cases such as entities are retrieved from a cache the relationships are not found. This will cause problems while updating the entity. In order to resolve this issue we can call loadRelations method of the mapper. But this triggers an error if self::$relationFields[$entityName] is not set
> Fix for error when calling mapper loadRelations method manually for entities loaded from a cache instead of DB

- composer.json
Hi,
I've changed the dependency requirements against `doctrine/dbal` so that it can use `v2.5.5`
I've run the test on php7 so far : 
```
$ php vendor/phpunit/phpunit/phpunit -c phpunit_mysql.xml                                                                                                                                                                                  PHPUnit 4.8.27 by Sebastian Bergmann and contributors.
...............................................................  63 / 198 ( 31%)
............................................................... 126 / 198 ( 63%)
............................................................... 189 / 198 ( 95%)
.........
Time: 1.75 seconds, Memory: 12.00MB
OK (198 tests, 418 assertions)
```
> FEATURE: Update doctrine/dbal depedency

- lib/Entity/Manager.php
- tests/Entity/MultipleIndexedField.php
- tests/Manager.php
This PR slightly modifies the 'index' argument of a field definition.
It allows to define compound index on fields that are already in other index scope.
``` PHP
<?php
namespace SpotTest\Entity;
use Spot\Entity;
/**
* Entity with fields in compound index and in non-compound index
*
* @package Spot
*/
class MultipleIndexedField extends \Spot\Entity
{
protected static $table = 'test_multipleindexedfield';
public static function fields()
{
return [
'id'            => ['type' => 'integer', 'primary' => true],
'companyGroup'  => ['type' => 'integer', 'required' => false, 'index' => true],
'company'       => ['type' => 'integer', 'required' => false, 'index' => [true, 'employee']],
'user'          => ['type' => 'string', 'required' => false, 'index' => [true, 'employee']],
];
}
}
```
```
$ …
```
> FEATURE: Allows field to be indexed in multiple compound indexes

- .travis.yml
- README.md
This PR adds PHP 7.1 and HHVM to tested versions. Both are allowed to fail at the moment. There will be a separate PR for fixing the build for PHP 7.1. Also corrects the Travis badge URL.
> Test PHP 7.1 and HHVM

- lib/Config.php
Documentation on [Link](http://phpdatamapper.com/docs/database-setup/) has an example to add a connection via an array. The method doc for addConnection says that the second param must be of type string, but this is not true. Some could either pass an Array, a String, or an instance of DBAL\Connection so I updated the param type to reflect this.
I found this problem because PHPStorm gave me a notice abut this.
Also fixed a typo for the default param.
> Allow dsn in addConnection to be of type Array or DBAL\Connection

- lib/Mapper.php
- tests/Entity/MultipleUniques.php
- tests/MultipleUniques.php
I was in a position I needed a field to be part of two different unique keys, and the validation of the entity when saving was failing as such.
So this PR serves the purpose of multiple unique keys per field.
This is not a huge change code-wise, and I provided some tests for the feature.
Regards.
> Validating multiples unique keys

- lib/Mapper.php
- lib/Query/Resolver.php
- tests/Entity/Legacy.php
- tests/FieldAlias.php
> lib/Mapper.php
If we have an entity defined with field alias mapping then in the `$data` array the value will be referenced by the aliased name. After the `array_intersect_key($data, $fields)` filter it seems that the aliased column is not in the entity definition, but that is not true.
I provided tests for this bug in my first commit and after applying my patch in the second commit the tests passed successfully.
You can find more details inside the mentioned issues (#237, #145).
> Fix for alias mapping bug

- lib/Query.php
- tests/DriverSpecific.php
- tests/FieldAlias.php
- tests/QuerySql.php
It would be really nice if you could order by a built-in (or user-defined) driver function. Currently ```count()``` and ```group()``` only works with fields specified in the entity's definition because ```fieldAliasMapping()``` appends the tableName before the fieldName. If the fieldName happens to be a function then it does not work. I implemented a simple "function detector" that works with one parameter (mysql) functions. It does not work with complex functions.
This way you can do something like this:
```php
$mapper->all()->order(['WEEK(date)' => 'ASC', 'priority' => 'DESC']);
```
It translates to this:
```mysql
ORDER BY WEEK(table.date) ASC, priority DESC
```
instead of 
```mysql
ORDER BY table.WEEK(date) ASC, priority DESC
```
This is 100% backwards compatible and it does not break …
> Implemented support for ordering by functions

- lib/Config.php
PHP >= 7.2 generates warning "count(): Parameter must be an array or an object that implements Countable"
> PHP >= 7.2 generates warning "count(): Parameter must be an array or an object that implements Countable"

- lib/Entity.php
This fixes a memory leak in the Entity class.
In my case, this represented ~3kB per Entity (which has around 40 relations).
I don't think tests are needed for this PR.
> FIx memory leak in Entity

- lib/Entity.php
In this fix, isset() is used instead of in_array() to test for the
existence of fields added to $this->_inGetter and $this->_inSetter.
This is because fields are added to these arrays as keys rather than
values.
> Fix Spot\Entity custom setter and getter infinite loop prevention
